--Q1 What is the total revenue generated by male vs female customers ?
select sum(purchase_amount) as total_revenue ,gender from MyTable group by gender ;

--Q2 which customers used a discount but still spend more than the average parchase amount ?
select customer_id , purchase_amount from MyTable 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from MyTable);

--Q3 which are the top 5 products with the highest average review rating ?

select top 5 item_purchased , cast(avg(review_rating)as decimal(10,2) )as Reviews from MyTable group by item_purchased order by Reviews desc

--Q4 compare the average purchase amounts between standard and express shipping ?
select avg (purchase_amount ) as Average_Purchase , shipping_type from MyTable
where shipping_type in ('Express','Standard')
group by shipping_type

--Q5 Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non- subscribers.
select subscription_status , avg(purchase_amount) as Average_Spend ,
sum(purchase_amount) as Total_revenue , count(customer_id) as Total_Customers
from MyTable group by subscription_status order by Total_revenue , Average_Spend desc

--Q Which 5 products generate the highest percentage of total revenue from discounted purchases?
    SELECT TOP 5 
    item_purchased,
    SUM(purchase_amount) AS Total_Revenue,
    SUM(purchase_amount) * 100.0 / 
    (SELECT SUM(purchase_amount) 
     FROM MyTable 
     WHERE discount_applied = 'Yes') AS Revenue_Percentage
FROM MyTable
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY Total_Revenue DESC;

--Q6 which 5 products have the highest percentage of purchases with discounts applied ?

select Top 5 item_purchased , sum(case when discount_applied = 'Yes' then 1 else 0 end)*100 /count(*) as dicount_rate
from MyTable group by item_purchased
order by dicount_rate desc 


--Q7 segment customers into New , Returning , and Loyal based on their total 
--number of previous purchases , and show the count of each segment.

select 
    count(customer_id) as total_customers,
    case 
        when previous_purchases = 1 then 'New'
        when previous_purchases between 2 AND 10 then 'Returning'
        else 'Loyal'
    end as customer_segment
from MyTable
group by 
    case 
        when previous_purchases = 1 then 'New'
        when previous_purchases between 2 AND 10 then 'Returning'
        else 'Loyal'
    end

--Q8 what are the top 3 most purchased products within each category ?

select*from MyTable
with item_counts as (

select category , item_purchased, count(customer_id) as total_orders , 
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from MyTable
group by category , item_purchased )

select item_rank , category , item_purchased , total_orders from item_counts where item_rank <= 3 ;

--Q9 Are  customers who are repeat buyers (more than 5 previous purchases) also Likely to subscribe ?

select count(customer_id) as repeat_buyers , subscription_status from MyTable 
where previous_purchases > 5 group by subscription_status

--Q10 what is the revenue contribution of each age group ?

select sum (purchase_amount) as Total_Revenue ,age_group from MyTable group by age_group order by Total_Revenue desc

